sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn lint
  - yarn pretty
  - yarn build:testapp
  - yarn test
  - yarn test:async:node8
  - yarn readme:validate
