sudo: required
dist: trusty
env:
  - MOZ_HEADLESS=1
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  firefox: latest
language: node_js
node_js:
    - 8 # LTS
    - 10
before_install:
    - yarn global add greenkeeper-lockfile@1
before_script:
    - greenkeeper-lockfile-update
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
after_script: greenkeeper-lockfile-upload
cache:
  yarn: true
  directories:
      - node_modules
install:
    - yarn
script:
    - yarn lint
    - yarn pretty
    - yarn build:testapp
    - yarn test:ci
    - '[[ $(node -v) =~ ^v6.*$ ]] || yarn test:async:node8' #skip on Node 6
    - yarn readme:validate
